[package]
name = "vertigo_devtools"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_flycam = "0.16.1"
bevy_voxel_world = { version = "0.12.0", features = ["noise"] }
noise = "0.9.0"
rand = "0.9.2"
